### ISSUE TITLE
tmux上のvimでctrl+hが使えない(効かない)

### ISSUE THREAD

**Issue by iranika** [kamaboko123/dotfiles#2]
https://github.com/kamaboko123/dotfiles/blob/master/.vimrc#L135

tmux上のvimだと`ctrl+h`で1単語戻るができない。tmuxじゃなければできる。
たぶんtmuxのキーバインドが邪魔してるっぽい。
tmux上では大人しくbで1単語戻るしかないのか？

**Comment by kamaboko123** [comment]
わしの環境では動く

**Comment by kamaboko123** [comment]
一部の環境ではCtrl+HがBackspaceとして扱われるので、Backspace向けのバインドも追加した。
これで動くかも
#3

**Comment by iranika** [comment]
すみませんが、
これターミナルソフト(RLogin)のせいっぽいです。。。
他のやつで正常に使えることが確認できました。

くそみたいなissue上げてすみませんでした。
